name: Penghijauan

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Menjalankan setiap jam (opsional)

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tambahkan perubahan (Update timestamp di Next.js)
        run: |
          echo "Membuat folder public jika belum ada..."
          mkdir -p public
          echo "Last run: $(date)" > public/timestamp.txt
          echo "Isi file timestamp.txt:"
          cat public/timestamp.txt  # Untuk debugging, pastikan file berisi data yang benar

      - name: Cek status sebelum commit
        run: |
          echo "Menampilkan status git:"
          git status
          echo "File yang ada di public folder:"
          ls public

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: "Siram Tanaman - Auto Update"
          branch: feature-123
          commit_options: '--no-verify --signoff'
          file_pattern: 'public/timestamp.txt'
          repository: .
          commit_user_name: "MFathinHalim"
          commit_user_email: "halimfathin7@gmail.com"
          commit_author: "MFathinHalim <MFathinHalim@github.com>"
          tagging_message: 'v1.0.0'
          status_options: ''
          add_options: '-A'
          push_options: '--force'
          skip_dirty_check: false
          skip_fetch: true
          skip_checkout: true
          disable_globbing: true
          create_branch: true
